// Generated by tools/license_generator.
// This file contains the public key only. Never place the private key in lib/.

abstract final class LicensePublicKey {
  static const String keyId = 'ed25519-main-v1';
  static const String algorithm = 'Ed25519';
  static const List<int> bytes = <int>[
    125,
    44,
    99,
    83,
    43,
    214,
    136,
    171,
    173,
    49,
    126,
    116,
    24,
    64,
    37,
    149,
    6,
    245,
    16,
    17,
    247,
    121,
    173,
    129,
    146,
    78,
    80,
    242,
    217,
    68,
    157,
    17,
  ];
}
